### ISSUE TITLE
网络添加resnet模型

### ISSUE THREAD

**Issue by WallZFE** [wlguan/MobileNet-v2-pruning#6]
您好，谢谢您分享pruning的操作，我现在尝试pruning resnet18模型，按照你的代码进行修改，已经成功pruner.prune(ckpt=None)了，但在测试计算量和大小的时候，出现了这个错误：RuntimeError: expected stride to be a single integer value or a list of 1 values to match the convolution dimensions, but got stride=[1, 1]
我查询了网上的解决方案，都不可以，我怀疑是我写的pruning代码有问题，您后面会添加resnet模型做主干网络吗？谢谢。

**Comment by apxlwl** [comment]
你好，最近就会更新resnet的，两周之内。

**Comment by WallZFE** [comment]
嗯嗯，谢谢您，十分感谢

**Comment by apxlwl** [comment]
> 您好，谢谢您分享pruning的操作，我现在尝试pruning resnet18模型，按照你的代码进行修改，已经成功pruner.prune(ckpt=None)了，但在测试计算量和大小的时候，出现了这个错误：RuntimeError: expected stride to be a single integer value or a list of 1 values to match the convolution dimensions, but got stride=[1, 1]
> 我查询了网上的解决方案，都不可以，我怀疑是我写的pruning代码有问题，您后面会添加resnet模型做主干网络吗？谢谢。

已更新

**Comment by WallZFE** [comment]
好的，十分感谢
